export const ENV = {
  hanaHost: process.env.HANA_HOST ?? "",
  hanaPort: process.env.HANA_PORT ?? "",
  hanaUser: process.env.HANA_USER ?? "",
  hanaPassword: process.env.HANA_PASSWORD ?? "",
  hanaSchema: process.env.HANA_SCHEMA ?? "SBO_HELEXIA",
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
};
